spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=app
    username: postgres
    password: password
    hikari:
      auto-commit: true
      schema: app
  flyway:
    enabled: true
    locations: classpath:/db/migration
    baselineOnMigrate: true
    validateOnMigrate: true
    fail-on-missing-locations: true
    validate-migration-naming: true
    user: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: app
#        envers:
#          audit_table_suffix: _AUD
#          audit_table_prefix:
#          revision_field_name: REV_ID
#          revision_type_field_name: REV_TYPE
#          store_data_at_delete: true


security:
  jwt:
    secret-key: 6f919b6e0aeca2f59ff2665115ac63906b8aeb32635afd86566b118b3d840f5a
    expiration-time: 720000

logging:
  level:
    org.springframework.security.web: DEBUG
    org.springframework.context.annotation: DEBUG